[build]
  command = "npm run build"
  functions = "functions" 
  publish = "dist" # 프로젝트 빌드 결과의 디렉토리를 지정합니다

[dev]
  framework = "#custom"
  command = "npm run dev:webpack"
  targetPort = 8079 
  port = 8080 
  publish = "dist"
  autoLaunch = false 